version: '3.7'

services:
  gitlab:
      restart: always
      image: sameersbn/gitlab:12.7.7
      env_file: 
        .env
      volumes:
        - /opt/gitlab/:/home/git/data:Z
      network_mode: "host"
  
  nexus:
      restart: always
      image: sonatype/nexus
      volumes:
        - "/opt/nexus/:/sonatype-work"
      env_file: 
        .env
      network_mode: "host"

  teamcity:
      restart: always
      image: jetbrains/teamcity-server
      env_file: 
          .env
      volumes:
        - /opt/teamcity/data_dir:/data/teamcity_server/datadir
        - /opt/teamcity/log_dir:/opt/teamcity/logs
      network_mode: "host"

  teamcity-agent:
      image: jetbrains/teamcity-agent
      environment:
        - SERVER_URL=http://10.10.0.3:8111
        - AGENT_NAME=regular_agent
      network_mode: "host"
