version: '3.7'

services:
   gitlab:
      restart: always
      image: sameersbn/gitlab:12.7.7
      ports:
        - "10080:80"
        - "10022:22"
      volumes:
        - gitlab-data:/home/git/data:Z
      network_mode: "host"
  
      