version: '3.7'

services:
   teamcity:
    image: jetbrains/teamcity-server
    ports:
      - 8111:8111
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs